r"""

================================================================================
Auto generated by mod2doctest on Fri Sep 24 13:47:51 2010
================================================================================
Python 2.6.2 (r262:71605, Apr 14 2009, 22:40:02) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> print 'start'
start
>>> 
>>> print '\n'

"""

if __name__ == '__main__':
    import doctest
    doctest.testmod(optionflags=524)

