r"""
================================================================================
Auto generated by mod2doctest on Sat Sep 25 15:51:41 2010
================================================================================
Python 2.6.2 (r262:71605, Apr 14 2009, 22:40:02) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> print 'start'
start
>>> 
>>> print '\n'


>>> 
>>> print 'foobar'
foobar
>>> 
>>> print '\n\n'



>>> 
>>> print 'baz'
baz
>>> 
>>> print ''

>>> 
>>> print 'foobarbaz'
foobarbaz
>>> 
>>> print ' '
 
>>> 
>>> print 'end'
end

"""

if __name__ == '__main__':
    import doctest
    doctest.testmod(optionflags=524)

