r"""


================================================================================
Auto generated by mod2doctest on Tue Sep 21 19:05:37 2010
================================================================================Type "help", "copyright", "credits" or "license" for more information.
>>> print 'start'
start
>>> 
>>> print '\n'

>>> 
>>> print 'foobar'
foobar
>>> 
>>> print '\n\n'


>>> 
>>> print 'baz'
baz
>>> 
>>> print ''
>>> 
>>> print 'foobarbaz'
foobarbaz
>>> 
>>> print ' '
 
>>> 
>>> print 'end'
end
>>>
"""

if __name__ == '__main__':
    import doctest
    doctest.testmod(optionflags=524)

