r"""

================================================================================
Auto generated by mod2doctest on Fri Sep 24 13:46:57 2010
================================================================================
Python 2.6.2 (r262:71605, Apr 14 2009, 22:40:02) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> class Foobar(object):
...     
...     def __init__(self, i):
...         print 'Hi #%d.' % i
>>> 
>>> for i in range(2):
...     print Foobar(i)
... for i in range(3):
  File "<stdin>", line 3
    for i in range(3):
      ^
SyntaxError: invalid syntax
>>>     print Foobar(i)
  File "<stdin>", line 1
    print Foobar(i)
    ^
IndentationError: unexpected indent
>>> 
>>> class Baz(object):
...     
...     def __init__(self, i):
...         print 'Bye #%d.' % i
... for i in range(3):
  File "<stdin>", line 6
    for i in range(3):
      ^
SyntaxError: invalid syntax
>>>     print Baz(i)
  File "<stdin>", line 1
    print Baz(i)
    ^
IndentationError: unexpected indent
>>> 
>>> def doit():
...     print 'did it ..'
... 
>>> for i in range(2):
...     print doit()
... 
did it ..
None
did it ..
None
>>> try:
...     print 'foobar' + 1
... except:
...     print 'foobar'
... finally:
...     print 'foobar' + 'foobar'
... 
foobar
foobarfoobar
>>> print 'hi'
hi

"""

if __name__ == '__main__':
    import doctest
    doctest.testmod(optionflags=524)

