r"""
================================================================================
Auto generated by mod2doctest on Sat Sep 25 15:51:56 2010
================================================================================
Python 2.6.2 (r262:71605, Apr 14 2009, 22:40:02) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> class Foobar(object):
...     
...     def __init__(self, i):
...         print 'Hi #%d.' % i
>>> 
>>> for i in range(2):
...     print Foobar(i)
... 
Hi #0.
<...Foobar object at 0x...>
Hi #1.
<...Foobar object at 0x...>
>>> for i in range(3):
...     print Foobar(i)
... 
Hi #0.
<...Foobar object at 0x...>
Hi #1.
<...Foobar object at 0x...>
Hi #2.
<...Foobar object at 0x...>
>>> 
>>> class Baz(object):
...     
...     def __init__(self, i):
...         print 'Bye #%d.' % i
... 
>>> for i in range(3):
...     print Baz(i)
... 
Bye #0.
<...Baz object at 0x...>
Bye #1.
<...Baz object at 0x...>
Bye #2.
<...Baz object at 0x...>
>>> def doit():
...     print 'did it ..'
... 
>>> for i in range(2):
...     print doit()
... 
did it ..
None
did it ..
None
>>> try:
...     print 'foobar' + 1
... except:
...     print 'foobar'
... finally:
...     print 'foobar' + 'foobar'
... 
foobar
foobarfoobar
>>> print 'hi'
hi

"""

if __name__ == '__main__':
    import doctest
    doctest.testmod(optionflags=524)

