r"""
================================================================================
Auto generated by mod2doctest on Thu Sep 23 13:25:41 2010
================================================================================
Welcome to mod2doctest
------------------------------------------------------------------------------

Just enter in some python
 
.. warning::  
   make sure to examine your resulting docstr to make sure output is as 
   expected!






The basics: 


>>> print 'Hello World!'
Hello World!
>>> 




Extended Example
------------------------------------------------------------------------------
A little more:


>>> somelist = [100, 2, -20, 340, 0, 0, 10, 10, 88, -3, 100, 2, -99, -1]
>>> sorted(set(somelist))
[-99, -20, -3, -1, 0, 2, 10, 88, 100, 340]
>>>
"""

